site_name: AGILPLAS ROSE-AP
site_url: https://github.com/ramp-eu/AGILPLAS
repo_url: https://github.com/ramp-eu/AGILPLAS
site_description: AGILPLAS ROSE-AP Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
nav:
  - Home: 'README.md'
  - Step by Step: 'stepbystep.md'
  - User & Programmers Manual:
    - 'Architecture' : 'architecture.md'
    - 'User Guide': 'usermanual.md'
    - 'API' : 'api.md'
    - 'How to Contribute': 'CONTRIBUTING.md'
  - 'Installation & Administration Manual':
    - 'Installation Guide': 'installationguide.md'
